name: Check linting

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8.3.1
    # - uses: actions/checkout@v2

    - name: Install modules
      run: pnpm install --legacy-peer-deps

    - name: Run ESLint
      run: npx eslint src/ --max-warnings=0