name: Check linting

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install modules
      run: npm install --legacy-peer-deps

    - name: Run vitest
      run: npx vitest