name: Deploy to gh-pages

env:
  VITE_APP_PRODUCTION: ${{secrets.REACT_APP_PRODUCTION}}
  VITE_API_HOST: ${{secrets.REACT_APP_API_HOST}}

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
      - uses: pnpm/action-setup@v2
        # uses: actions/checkout@v1

      - name: Install and build
        run: pnpm install --legacy-peer-deps && pnpm run build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build